name: Ejecutar Scraper

on:
  schedule:
    - cron: '*/30 * * * *'  # Cada 30 minutos
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup ChromeDriver
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar scraper
        env:
          WEB_APP_URL: ${{ secrets.WEB_APP_URL }}
        run: |
          python main.py

      - name: Guardar cambios en el repositorio
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pendientes_incidentes.json resultado_incidentes.json
          git diff --staged --quiet || git commit -m "📊 Actualizar estado automático"
          git push